version: '2.29.7'

services:
  web:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOSTNAME : ${database_hostname}
      DATABASE_URL: "postgresql://${database_username}:${database_password}@db:5432/${database_name}"
      SECRET_KEY: ${secret_key}
      ALGORITHM: ${algorithm}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${access_token_expire_minutes}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
    depends_on:
      - db


  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${database_username}
      POSTGRES_PASSWORD: ${database_password}
      POSTGRES_DB: ${database_name}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data: