"""Update OTP model

Revision ID: f1d37b858761
Revises: f980bfb0b257
Create Date: 2024-05-23 17:34:52.569205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1d37b858761'
down_revision: Union[str, None] = 'f980bfb0b257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('expiration_time', sa.DateTime(), nullable=False))
    op.drop_column('otps', 'expiration_timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('expiration_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('otps', 'expiration_time')
    # ### end Alembic commands ###
